"""
core.api.routes.ws
===================
WebSocket endpoint for real-time alert streaming.

Security relevance:
    WebSocket connections bypass standard HTTP middleware.  In production:

    1. **Authentication** — WebSocket upgrade requests should include an
       API key in the query string or first message.  The current
       implementation is open for development convenience.

    2. **Rate limiting** — the server broadcasts all alerts; a misbehaving
       client cannot cause backpressure.  Broadcasting uses non-blocking
       ``send_json`` with error handling per client.

    3. **Connection limits** — ``MAX_WS_CONNECTIONS`` caps the simultaneous
       connection count to prevent resource exhaustion.
"""

from __future__ import annotations

import asyncio
import logging

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

logger = logging.getLogger(__name__)

router = APIRouter()

# Active WebSocket connections
_connections: set[WebSocket] = set()
_MAX_CONNECTIONS: int = 50


@router.websocket("/ws/alerts")
async def websocket_alerts(websocket: WebSocket) -> None:
    """WebSocket endpoint for real-time alert streaming.

    Clients connect to ``ws://<host>/ws/alerts`` and receive JSON
    alert objects as they are generated by the detection pipeline.

    Protocol:
        - Server sends: JSON ``AlertResponse`` objects on each new alert.
        - Client sends: ``ping`` frames (handled by FastAPI/Starlette).
        - Server closes: On error, client disconnect, or shutdown.

    Security note:
        No authentication on the WebSocket upgrade.  In production,
        require an API key in the query string for connection approval.
    """
    if len(_connections) >= _MAX_CONNECTIONS:
        await websocket.close(code=1013, reason="Too many connections")
        return

    await websocket.accept()
    _connections.add(websocket)
    logger.info(
        "WebSocket client connected (total: %d)", len(_connections)
    )

    try:
        while True:
            # Keep connection alive — wait for client messages or disconnect
            data = await websocket.receive_text()
            # Echo back pong for custom ping
            if data == "ping":
                await websocket.send_text("pong")
    except WebSocketDisconnect:
        pass
    except Exception as exc:
        logger.debug("WebSocket error: %s", exc)
    finally:
        _connections.discard(websocket)
        logger.info(
            "WebSocket client disconnected (remaining: %d)",
            len(_connections),
        )


async def broadcast_alert(alert_data: dict) -> None:
    """Broadcast an alert to all connected WebSocket clients.

    Args:
        alert_data: Serialised alert dict matching ``AlertResponse``.

    Non-blocking: failures on individual clients are caught and the
    client is removed silently.  Broadcasting never blocks the detection
    pipeline.
    """
    if not _connections:
        return

    dead: set[WebSocket] = set()
    for ws in _connections.copy():
        try:
            await ws.send_json(alert_data)
        except Exception:
            dead.add(ws)

    _connections.difference_update(dead)
    if dead:
        logger.debug(
            "Removed %d dead WebSocket connection(s)", len(dead)
        )


def get_connection_count() -> int:
    """Return the number of active WebSocket connections."""
    return len(_connections)
